version: 0.2

env:
  secrets-manager:
    github_pat: github_pat

phases:
  install: 
    runtime-versions: 
      python: 3.9
  pre_build:
    commands:
      - echo $github_pat | docker login ghcr.io -u yellowmamba --password-stdin
  build:
    commands:
      - echo Building an image $IMAGE_TAGS for `uname -m`
      - docker build -t python39 .
      - |
        tags=($IMAGE_TAGS)
        for tag in "${tags[@]}"
        do
            echo building $tag
            docker tag python39 $tag
            docker push $tag
        done
      - docker images

  post_build:
    commands:
      - echo Build completed!