version: 0.2

phases:
  install: 
    runtime-versions: 
      python: 3.9
  pre_build:
    commands:
      - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION
  build:
    commands:
      - docker build -t $ECR_REPO:$ARCH .
      - docker tag $ECR_REPO:$ARCH public.ecr.aws/x2n1n8d5/$ECR_REPO:$ARCH
  post_build:
    commands:
      - echo pushing to ECR...
      - docker push public.ecr.aws/x2n1n8d5/$ECR_REPO:$ARCH