version: 0.2

phases:
  install: 
    runtime-versions: 
      python: 3.9
  build:
    commands:
      - echo Building an image $IMAGE_TAGS for `uname -m`
  post_build:
    commands:
      - echo Build completed!