version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - docker build -t $ECR_REPO:$ARCH .
      - docker tag $ECR_REPO:$ARCH public.ecr.aws/x2n1n8d5/$ECR_REPO:$ARCH
  post_build:
    commands:
      - echo pushing to ECR...
      - docker push public.ecr.aws/x2n1n8d5/$ECR_REPO:$ARCH