version: 0.2

phases:
  install: 
    runtime-versions: 
      python: 3.9
  build:
    commands:
      - echo Build docker image for `uname -m`
      - echo `docker version`
  post_build:
    commands:
      - echo Build completed!