version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR Public...
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker manifest...   
            - export DOCKER_CLI_EXPERIMENTAL=enabled       
            - docker manifest create public.ecr.aws/x2n1n8d5/$ECR_REPO:$RELEASE_DATE public.ecr.aws/x2n1n8d5/$ECR_REPO:arm64 public.ecr.aws/x2n1n8d5/$ECR_REPO:amd64
            - docker manifest inspect public.ecr.aws/x2n1n8d5/$ECR_REPO:$RELEASE_DATE

    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker manifest push public.ecr.aws/x2n1n8d5/$ECR_REPO:$RELEASE_DATE
