name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    # forGitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/yellowmamba/python
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=3.9

      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: test-docker-build
          buildspec-override: ../../buildspec.yml