name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

# forGitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            multi-arch-python3.9
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=sha

  build-x86:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-x86
          buildspec-override: buildspec.yml
          env-vars-for-codebuild: |
            ARCH,
            ECR_REPO,
            AWS_ACCOUNT_ID,
            AWS_DEFAULT_REGION
        env:
          ARCH: amd64
          ECR_REPO: multi-arch-python3.9
          AWS_ACCOUNT_ID: 168942669170
          AWS_DEFAULT_REGION: ap-southeast-2

  build-graviton2:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-graviton2
          buildspec-override: buildspec.yml
          env-vars-for-codebuild: |
            ARCH,
            ECR_REPO,
            AWS_ACCOUNT_ID,
            AWS_DEFAULT_REGION
        env:
          ARCH: arm64
          ECR_REPO: multi-arch-python3.9
          AWS_ACCOUNT_ID: 168942669170
          AWS_DEFAULT_REGION: ap-southeast-2
  
  create-image-manifest:
    runs-on: ubuntu-latest
    needs: [build-x86, build-graviton2]
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-graviton2
          buildspec-override: buildspec.yml
          env-vars-for-codebuild: |
            ARCH,
            ECR_REPO,
            AWS_ACCOUNT_ID,
            AWS_DEFAULT_REGION
        env:
          ECR_REPO: multi-arch-python3.9
          AWS_ACCOUNT_ID: 168942669170
          AWS_DEFAULT_REGION: ap-southeast-2
          IMAGE_TAG: ${{ needs.prepare.outputs.image_tags }}