name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

# forGitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/yellowmamba/python3.9
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=3.9
  
  build-x86:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Debug
        run: |
          echo docker image version is ${{ needs.prepare.outputs.image_version }}
          echo docker image version is ${{ needs.prepare.outputs.image_tags }}
      
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-x86
          buildspec-override: buildspec.yml

  build-graviton2:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Debug
        run: |
          echo docker image version is ${{ needs.prepare.outputs.image_version }}
          echo docker image version is ${{ needs.prepare.outputs.image_tags }}

      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-graviton2
          buildspec-override: buildspec.yml