name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

# forGitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

  build-x86:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-x86
          buildspec-override: buildspec.yml
          env-vars-for-codebuild: |
            ARCH,
            ECR_REPO
        env:
          ARCH: amd64
          ECR_REPO: multi-arch-python3.9

  build-graviton2:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-build-graviton2
          buildspec-override: buildspec.yml
          env-vars-for-codebuild: |
            ARCH,
            ECR_REPO
        env:
          ARCH: arm64
          ECR_REPO: multi-arch-python3.9
  
  create-image-manifest:
    runs-on: ubuntu-latest
    needs: [build-x86, build-graviton2]
    steps:
      - name: Obtain AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::168942669170:role/github-codebuild-role
          aws-region: ap-southeast-2

      - name: Launch CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-manifest
          env-vars-for-codebuild: |
            ECR_REPO,
            RELEASE_DATE
        env:
          ECR_REPO: multi-arch-python3.9
          RELEASE_DATE: ${{ steps.date.outputs.date }}